import { NextResponse } from "next/server";
import { getData, id, saveData, audit } from "@/lib/store";
export async function POST() { const data = await getData(); if (data.projects.length) return NextResponse.json(data);
 const tenant = { id: id(), name: "Greenview CHS", type: "SOCIETY" as const, gstin: "27AABCG1234A1Z5" }; const admin = { id: id(), tenantId: tenant.id, name: "Foxscan Admin", email: "kshirsagarsahil414@gmail.com", role: "ADMIN" as const, active: true };
 const contractor = { id: id(), tenantId: tenant.id, name: "Apex Coatings", email: "kshirsagarsahil143@gmail.com", role: "CONTRACTOR" as const, active: true }; const manufacturer = { id: id(), tenantId: tenant.id, name: "Asian Paints Rep", email: "kshirsagarsahil0704@gmail.com", role: "MANUFACTURER" as const, active: true }; const consultant = { id: id(), tenantId: tenant.id, name: "Foxscan PMC", email: "kshirsagarsahil149@gmail.com", role: "CONSULTANT" as const, active: true }; const client = { id: id(), tenantId: tenant.id, name: "Greenview Secretary", email: "moviesdrives6969@gmail.com", role: "CLIENT" as const, active: true };
 const project = { id: id(), tenantId: tenant.id, name: "Greenview External Repainting", address: "Pune, Maharashtra", scope: "External painting and crack repair", buildings: 3, areaSqft: 96000, contractValue: 3800000, startDate: "2026-07-01", endDate: "2026-11-30", status: "ACTIVE" as const, contractorId: contractor.id, manufacturerId: manufacturer.id, consultantId: consultant.id, clientId: client.id };
 data.tenants.push(tenant); data.users.push(admin, contractor, manufacturer, consultant, client); data.projects.push(project); data.buildings.push({id:id(),projectId:project.id,name:"Tower A",wings:2,floors:20,areaSqft:32000},{id:id(),projectId:project.id,name:"Tower B",wings:2,floors:20,areaSqft:32000},{id:id(),projectId:project.id,name:"Tower C",wings:2,floors:20,areaSqft:32000});
 for (const [sequence, name, value] of [[1,"Mobilization + scaffolding",380000],[2,"Surface preparation & crack filling",570000],[3,"Primer application",380000],[4,"Putty + first coat",760000],[5,"Second & final coat",760000],[6,"Scaffolding removal & cleanup",570000]] as const) data.activities.push({ id:id(), projectId:project.id, name, sequence, plannedStart:"2026-07-01", plannedEnd:"2026-08-01", progress: sequence === 1 ? 100 : 0, status: sequence === 1 ? "PAID" : "NOT_STARTED", dependencyIds:[], paymentMode:"FIXED", paymentValue:value, retentionPct:10, gstPct:18 });
 data.boqItems.push({id:id(),projectId:project.id,code:"PAINT-001",description:"External acrylic coating",quantity:96000,unit:"sq.ft",rate:39.58,manufacturer:"Asian Paints",version:1}); data.documents.push({id:id(),projectId:project.id,name:"Signed contract",type:"CONTRACT",version:1,tags:["signed","contract"],visibility:["ADMIN","CLIENT","CONSULTANT","CONTRACTOR"],url:"local://contracts/greenview-v1.pdf",uploadedBy:admin.id,createdAt:new Date().toISOString()}); await audit(data, { tenantId: tenant.id, actorId: admin.id, action:"BOOTSTRAP", entity:"project", entityId:project.id, after:project }); await saveData(data); return NextResponse.json(data, { status: 201 }); }
