module.exports={
  content:["./app/**/*.{ts,tsx}","./components/**/*.{ts,tsx}"],
  presets:[require("nativewind/preset")],
  theme:{
    extend:{
      colors:{
        fox:"#EAAC1F",
        brandAmber:"#EAAC1F",
        brandCharcoal:"#1A1D24",
        offWhite:"#F9F9F6",
        successGreen:"#1B8755",
        alertRed:"#D9383A",
        mutedGray:"#64748B",
        ink:"#1A1D24"
      }
    }
  },
  plugins:[]
};
