import nodemailer from "nodemailer";
export type IntegrationStatus = { key: string; provider: string; enabled: boolean; mode: "live" | "fallback"; detail: string };
export type Notification = { to: string; subject: string; body: string };
export interface NotificationProvider { status(): IntegrationStatus; send(message: Notification): Promise<{ id: string; delivered: boolean }> }
class FallbackProvider implements NotificationProvider { constructor(protected key: string, protected provider: string, protected detail: string) {} status(): IntegrationStatus { return { key:this.key,provider:this.provider,enabled:false,mode:"fallback",detail:this.detail }; } async send(message:Notification){console.info(`[FOXSCAN:${this.key}]`,message);return{id:`local-${crypto.randomUUID()}`,delivered:true};} }
class AiSensyProvider extends FallbackProvider { constructor(){super("whatsapp","AiSensy","AiSensy credentials missing; in-app notification retained.");} override status():IntegrationStatus{return process.env.AISENSY_API_KEY?{key:this.key,provider:this.provider,enabled:true,mode:"live",detail:"Configured"}:super.status();} override async send(message:Notification){if(!process.env.AISENSY_API_KEY)return super.send(message);const response=await fetch("https://backend.aisensy.com/campaign/t1/api/v2",{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${process.env.AISENSY_API_KEY}`},body:JSON.stringify({campaignName:process.env.AISENSY_CAMPAIGN_NAME,recipientPhone:message.to,templateParams:[message.subject,message.body]})});if(!response.ok)throw new Error(`AiSensy failed: ${response.status}`);return{id:`aisensy-${crypto.randomUUID()}`,delivered:true};} }
class SmtpProvider extends FallbackProvider { constructor(){super("email","SMTP","SMTP credentials missing; in-app notification retained.");} override status():IntegrationStatus{return process.env.SMTP_HOST&&process.env.SMTP_FROM?{key:this.key,provider:this.provider,enabled:true,mode:"live",detail:"Configured"}:super.status();} override async send(message:Notification){if(!process.env.SMTP_HOST||!process.env.SMTP_FROM)return super.send(message);const transport=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==="true",auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,pass:process.env.SMTP_PASSWORD}:undefined});const result=await transport.sendMail({from:process.env.SMTP_FROM,to:message.to,subject:message.subject,text:message.body});return{id:result.messageId,delivered:true};} }
class FcmProvider extends FallbackProvider { constructor(){super("push","Firebase Cloud Messaging","Firebase service credentials missing; in-app notification retained.");} override status():IntegrationStatus{return process.env.FIREBASE_PROJECT_ID&&process.env.FIREBASE_ACCESS_TOKEN?{key:this.key,provider:this.provider,enabled:true,mode:"live",detail:"Configured"}:super.status();} override async send(message:Notification){if(!process.env.FIREBASE_PROJECT_ID||!process.env.FIREBASE_ACCESS_TOKEN)return super.send(message);const response=await fetch(`https://fcm.googleapis.com/v1/projects/${process.env.FIREBASE_PROJECT_ID}/messages:send`,{method:"POST",headers:{Authorization:`Bearer ${process.env.FIREBASE_ACCESS_TOKEN}`,"Content-Type":"application/json"},body:JSON.stringify({message:{token:message.to,notification:{title:message.subject,body:message.body}}})});if(!response.ok)throw new Error(`FCM failed: ${response.status}`);return{id:`fcm-${crypto.randomUUID()}`,delivered:true};} }
export const integrations={whatsapp:new AiSensyProvider(),email:new SmtpProvider(),push:new FcmProvider(),sms:new FallbackProvider("sms","Local fallback","No SMS gateway configured; in-app alerts remain active."),payments:new FallbackProvider("payments","Razorpay","Razorpay credentials missing; internal payment recording is active."),storage:new FallbackProvider("storage","Supabase Storage","Storage credentials missing; local document references remain active.")};
export function integrationStatuses(){return Object.values(integrations).map(provider=>provider.status());}
