-- Phase 4: DLP, warranties, disputes and hardened operational reporting.
create table public.dlp_cases(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,contractor_id uuid not null references public.profiles(id),starts_on date not null,ends_on date not null,inspection_due_on date not null,retention_amount numeric(16,2) not null default 0 check(retention_amount>=0),status text not null check(status in ('ACTIVE','INSPECTION_DUE','CLOSED','OVERDUE')),closed_at timestamptz,created_at timestamptz not null default now(),check(ends_on>=starts_on));
create table public.warranties(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,provider text not null,type text not null check(type in ('MANUFACTURER','WORKMANSHIP')),reference text not null,starts_on date not null,ends_on date not null,coverage text not null,document_id uuid references public.documents(id) on delete set null,status text not null check(status in ('ACTIVE','EXPIRING','EXPIRED')),created_at timestamptz not null default now(),check(ends_on>=starts_on),unique(project_id,reference));
create table public.disputes(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,raised_by uuid not null references public.profiles(id),category text not null check(category in ('QUALITY','PAYMENT','SCOPE','DELAY','SAFETY','OTHER')),title text not null,description text not null,status text not null check(status in ('OPEN','UNDER_REVIEW','RESOLVED','CLOSED')),owner_id uuid references public.profiles(id),resolution text,resolved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.dispute_evidence(dispute_id uuid not null references public.disputes(id) on delete cascade,document_id uuid not null references public.documents(id) on delete cascade,primary key(dispute_id,document_id));
create index dlp_cases_project_status_idx on public.dlp_cases(project_id,status,ends_on);create index warranties_project_status_idx on public.warranties(project_id,status,ends_on);create index disputes_project_status_idx on public.disputes(project_id,status,created_at desc);
alter table public.dlp_cases enable row level security;alter table public.warranties enable row level security;alter table public.disputes enable row level security;alter table public.dispute_evidence enable row level security;
create policy "dlp project access" on public.dlp_cases for all using(public.can_access_project(project_id)) with check(public.can_access_project(project_id));
create policy "warranty project access" on public.warranties for all using(public.can_access_project(project_id)) with check(public.can_access_project(project_id));
create policy "dispute project access" on public.disputes for all using(public.can_access_project(project_id)) with check(public.can_access_project(project_id));
create policy "dispute evidence access" on public.dispute_evidence for all using(exists(select 1 from public.disputes d where d.id=dispute_id and public.can_access_project(d.project_id))) with check(true);
create function public.touch_dispute() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end;$$;create trigger disputes_touch before update on public.disputes for each row execute function public.touch_dispute();
create function public.advanced_portfolio_report() returns table(project_id uuid,project_name text,contract_value numeric,progress numeric,overdue_stages bigint,open_disputes bigint,retention_held numeric) language sql stable security invoker set search_path=public as $$select p.id,p.name,p.contract_value,coalesce(avg(a.progress),0),count(distinct s.id) filter(where s.due_at<now() and s.state<>'PAID'),count(distinct d.id) filter(where d.status in ('OPEN','UNDER_REVIEW')),coalesce(sum(i.retention),0) from projects p left join activities a on a.project_id=p.id left join stages s on s.activity_id=a.id left join disputes d on d.project_id=p.id left join invoices i on i.project_id=p.id where can_access_project(p.id) group by p.id,p.name,p.contract_value$$;
